### Signup User and Create Account
POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "username": "Janaina",
    "password": "Jan1dfsdfs"
}

### Login Account
POST http://localhost:3003/account/login
Content-Type: application/json

{
    "username": "Vinicius",
    "password": "vinicius"
}

### Get Account By Id
GET http://localhost:3003/account/